const CartActionType= {
    TOGGEL_CART_HIDDEN:'TOGGEL_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM:'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CART_CLEAR: 'CART_CLEAR'
}

export default CartActionType;